version: "3.8"

services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # pgadmin:
  #   image: dcagatay/pwless-pgadmin4
  #   ports:
  #     - 5050:80
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_HOST: db
  #     POSTGRES_PORT: 5432
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin


volumes:
  pgdata:
  # pgadmin:
