import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { PropsWithChildren } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <section className="todoapp">{children}</section>
        <footer className="info">
            <p>Double-click to edit a todo</p>
            <p>
                Created by
                <a href="http://github.com/pabenest">Pierre Benest</a> and
                <a href="http://github.com/lsagetlethias">Lilian Saget-Lethias</a> using <a href="http://nextjs.org">Next.js</a>.
                Source code available on
                <a
                    href="https://github.com/pabenest/todo"
                    target="_blank"
                    >GitHub</a>
            </p>
            <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
        </footer>
      </body>
    </html>
  )
}
